(WIP) Add check runner
dcos/dcos-check-runner pull request #1
Opened 2018-05-23 22:17 UTC by branden

This adds the check runner from dcos/dcos-diagnostics.

https://jira.mesosphere.com/browse/DCOS_OSS-3491

2018-05-25 01:09 UTC, branden commented
I haven't figured out how to get Jenkins to automatically build PRs on this repo yet, but here's a build of 99bfddf that I ran manually: https://jenkins.mesosphere.com/service/jenkins/job/public-dcos-cluster-ops/job/dcos-check-runner/job/dcos-check-runner-pulls/2/

2018-05-25 20:08 UTC, amitaekbote commented
Did we test this against dcos?

2018-05-25 20:16 UTC, branden commented
@amitaekbote Not yet, my intention with this PR was just to get tests passing. I'll follow up with another PR if integrating with DC/OS reveals any problems. I don't intend to remove dcos-diagnostics' runner (https://github.com/dcos/dcos-diagnostics/pull/35) until this one is merged into DC/OS.

2018-05-25 20:21 UTC, amitaekbote submitted a review, later dismissed

2018-05-25 21:33 UTC, branden commented
Thanks @amitaekbote! @mnaboka PTAL when you get a chance, I'd like to get your eyes on this before I merge since you're so familiar with both golang and dcos-diagnostics.

2018-05-30 01:31 UTC, branden commented
DC/OS PR: https://github.com/dcos/dcos/pull/2921

2018-05-30 04:01 UTC, initcore0 requested changes
i also noticed you added this package 
`github.com/Sirupsen/logrus` which should actually be
`github.com/sirupsen/logrus` (lowercase sirupsen)

2018-05-30 04:01 UTC, mnaboka commented on Dockerfile
> +    libsystemd-dev
libsystemd-dev was a dcos-diagnostics dependency because it reads journald logs when systemd unit fails. I don't think check runner needs this, so it should be okay to remove it.

2018-05-30 18:46 UTC, branden commented
@mnaboka Thanks for catching that. That lib came from dcos-diagnostics -- should that repo be updated? https://github.com/dcos/dcos-diagnostics/blob/2487edc5cd43d63e7d13a91ef762d40b3ba044cc/vendor/vendor.json#L6

2018-05-30 18:49 UTC, mnaboka commented
@branden yes, i believe we should update all dependencies in dcos-diagnostics
i will take care of it!

2018-05-30 19:11 UTC, branden commented
@mnaboka @amitaekbote Comments addressed, PTAL!

2018-05-30 23:02 UTC, amitaekbote approved these changes

2018-05-31 20:23 UTC, initcore0 approved these changes

2018-05-31 20:24 UTC, merged