Run checks in parallel
dcos/dcos-check-runner pull request #3
Opened 2018-06-02 00:39 UTC by branden

This is a port of https://github.com/dcos/dcos-diagnostics/pull/33.

2018-06-04 14:57 UTC, gpaul commented
Nice one - would you mind addressing my last review comments over here, then?

2018-06-04 18:29 UTC, branden commented
@gpaul Sure thing. My priority is https://github.com/dcos/dcos/pull/2921, but I'll ping you when this is ready for a look.

2018-06-14 10:16 UTC, branden commented
@gpaul Feedback addressed, PTAL.

2018-06-14 10:38 UTC, gpaul commented on runner/runner.go
> +			results <- &responseCheck{name, false, "", false, resp}
You only want to send the "success" response if there was not error.

2018-06-14 10:40 UTC, gpaul commented on runner/runner.go
> +				combinedResponse.checkNotFound = result.checkNotFound
I think `combinedResponse.checkNotFound` should be true if _any_ check was "not found". If you agree, we need an `if` here or use `|=` instead of `=`.

2018-06-14 10:43 UTC, gpaul commented on runner/runner.go
> +			} else if result.err {
What do you think about combining `err` and `errMsg` in `responseCheck` then doing:

```
} else if err := result.err; err != nil {
  if result.response != nil {
    combinedResponse.errors[err.Error()] = result.response
  } else {
    combinedResponse.errs[err.Error()] = &Response{name: result.checkName}
  }
}
```

Also, what do you think about returning a `&Response{name: checkname}` from line 267, then you don't need this `else` clause at all.

2018-06-14 10:43 UTC, gpaul requested changes
I have a couple of suggestions and only one serious issue.

2018-06-14 17:04 UTC, branden commented on runner/runner.go
> +			} else if result.err {
I initially tried to treat `err` as an error message, and set it to `nil` if there's no error, but that caused this error:

> cannot use nil as type string in field value

So I split it up into a boolean `err` for indicating whether the response is an error, and an `errMsg` that contains the error message if `err` is `true`. Is there a simpler way to accomplish that?

2018-06-14 17:04 UTC, branden commented
Thanks for the feedback @gpaul. I just pushed some fixes and responded to a comment.

2018-06-14 17:16 UTC, gpaul submitted a review, later dismissed
This is fine to merge as-is.

As to your question regarding err and errMsg...

Instead of two fields `err bool` and `errMsg string`, I would have `err error`. Then, instead of checking `if result.err == true` (or the equivalent below) I would do `if result.err != nil`. And instead of `errMsg` I would use `err.Error()`.

Does that make sense?

2018-06-14 17:22 UTC, branden commented
That does make sense, thanks. I'll push that change and give you another chance to review before I merge this.

2018-06-14 22:46 UTC, branden commented
@gpaul I pushed a commit that replaces the `bool` and `string` with an `error`.

2018-06-15 15:52 UTC, gpaul approved these changes
LGTM!

2018-06-15 16:29 UTC, merged